name: Stage 2 - Build and Push Docker Image

on:
  push:
    branches:
      - master  # Change if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t bshivanya/img3:latest -t bshivanya/img3:${{ github.sha }} ./monitoring

      - name: Push Docker image
        run: |
          docker push bshivanya/img3:latest
          docker push bshivanya/img3:${{ github.sha }}


# name: Stage 2 - Build and Push Docker Image

# on:
#   push:
#     branches:
#       - master  # Change if your default branch is different

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     permissions:
#       contents: read
#       packages: write

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Log in to Docker Hub
#         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

#       - name: Build Docker image
#         run: |
#           docker build -t bshivanya/img3:latest -t bshivanya/img3:${{ github.sha }} .

#       - name: Push Docker image
#         run: |
#           docker push bshivanya/img3:latest
#           docker push bshivanya/img3:${{ github.sha }}


